include:                           
   - ./todo-frontend/docker-compose.dev.yml        
   - ./todo-backend/docker-compose.dev.yml 

services:
  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app